name 'gettyimages-jnuget'
version '0.0.1'
source 'https://github.com/gettyimages/puppet-jnuget'
author 'dylan.meisner@gettyimages.com'
license 'MIT'
summary 'Getty Images JNuget Module'
description 'JNuget Module for Puppet'
project_page 'https://github.com/gettyimages/puppet-jnuget'